# Index names
indices:
  source: locust-logs-*
  threat: threat-logs
  normal: normal-logs

# DDoS detection settings
ddos:
  threshold: 5
  time_window: 2
  max_requests: 1000

# Threat detection rules
detection_rules:
  sql_injection:
    - |-
      id=\s*['"].*?(?:--|\%27|')
    - |-
      UNION\s+SELECT
    - |-
      EXEC\s*\(
    - |-
      WAITFOR\s+DELAY
    - |-
      SELECT\s+.*?FROM
    - |-
      1\s*=\s*1
    - |-
      DROP\s+TABLE
    - |-
      ;.*?(?:SELECT|INSERT|UPDATE|DELETE|DROP)
  xss:
    - "<script>"
    - "javascript:"
    - "alert\\s*\\("
    - "on\\w+\\s*="
    - "<svg.*?on\\w+\\s*="
    - "<img.*?on\\w+\\s*="
    - "\"\\s*><script>"
    - "'\\s*><script>"
  path_traversal:
    - "\\.\\.\\/|\\.\\.\\\\"
    - "\\.\\.(\\%2f|\\%5c)"
    - "\\%2e\\%2e(\\%2f|\\%5c)"
    - "\\%252e\\%252e(\\%252f|\\%255c)"
  command_injection:
    - ";\\s*\\w+"
    - "`.*?`"
    - "\\|\\s*\\w+"
    - "\\$\\(.*?\\)"
    - "&&\\s*\\w+"
    - "\\|\\|\\s*\\w+"

# Log processing settings
processing:
  batch_size: 1000
  poll_interval: 5
  error_retry_interval: 30

# Logging configuration
logging:
  level: INFO
  file: /mnt/logs/threat_detector.log
  max_size: 10485760  # 10 MB
  backup_count: 5

# Field order for log entries
field_order:
  - log_id
  - threat_type
  - detected_threats
  - "@timestamp"
  - client_ip
  - method
  - url
  - status_code
  - response_time_ms
  - bytes_sent
  - bytes_received
  - user_agent
  - referer
  - request_headers
  - response_headers
  - geo
  - request_body
