elasticsearch:
  host: elasticsearch
  port: 9200
indices:
  threat: threat-logs
logging:
  backup_count: 5
  file: /mnt/logs/threat_responder.log
  level: INFO
  max_size: 10485760
processing:
  batch_size: 100
  error_retry_interval: 30
  poll_interval: 5
rate_limit:
  max_requests: 94
  window_size: 60
redis:
  blocked_ips_key: blocked_ips
  expiration_time: 3600
  key_prefix: 'threat_responder:'
  url: redis://redis:6379/0
response_actions:
  command_injection: block_ip
  ddos: block_ip
  path_traversal: log
  potential_brute_force: rate_limit
  potential_ddos: rate_limit
  sql_injection: block_ip
  xss: block_ip
sync_interval: 300
